# [------------------------------]
# [    qEssentials v0.1-DEV
# [  Dziêki za u¿ywanie! :)
# [  Wersja: PL / POLAND / POLSKA
# [------------------------------]

# [------------------------------]
# [      Podstawowe rzeczy 
# [------------------------------]
# Czy ma byæ w³¹czone szczegó³owe debugowanie (szczegó³owe informacje wysy³ane do konsoli)
debug: true
# Czy opcje wymagaj¹ce pluginu BarAPI maj¹ byæ w³¹czone
barapi: true
# G³ówne serwerowe motd
server-motd: '&7Plugin &cqEssentials &7by &cxVacuum&7!'
# Sloty (tylko wyœwietlane, nie prawdziwe!)
server-slots: 120
  
 
# [------------------------------]
# [            Chat 
# [------------------------------]
# Format chatu
chat-format: '&8[{PREFIX}&8] &f{PLAYER}&8: &7{MESSAGE}'
# Wiadomoœæ wy³¹czania chatu
chat-off: '&7Chat zostal &cwylaczony&7!'
# Wiadomoœæ w³¹czania chatu
chat-on: '&7Chat zostal &cwlaczony&7!'
# Wiadomoœæ czyszczenia chatu
chat-clear: '&7Chat zostal &cwyczyszczony&7!'
# Czy ma byæ w³¹czona blokada URL ( - BETA!)
url-block: true
# Czy ma byæ w³¹czona blokada IP ( - BETA!)
ip-block: true
# Czy ma byæ w³¹czona blokada przekleñstw i nazw popularnych serwerów 
words-block: true
# Format chatu administratora
adminchat-format: '&8[&4@&8] &7{PLAYER}: &c{MESSAGE}'

# [------------------------------]
# [           Helpop
# [------------------------------]
# Co ile sekund mo¿na wysy³aæ /helpop 
helpop-delay: 30
# Format helpopu
helpop-format: '&8[&4Helpop&8] &7{PLAYER}: &c{MESSAGE}'

# [------------------------------]
# [           ChangeItem
# [------------------------------]
# Czym ma sie usuwac nazwe itemu lub opis
changeitem-remove: '-remove'

# [------------------------------]
# [         Join/Leave
# [------------------------------]
# Format dolaczania na serwer (zostaw '' jezeli chcesz wylaczyc)
join-format: '&c{PLAYER} &7dolaczyl do gry!'
# Format opuszczania serwera (zostaw '' jezeli chcesz wylaczyc)
leave-format: '&c{PLAYER} &7opuscil gre!'

# [------------------------------]
# [         Teleportation
# [------------------------------]
# Okres oczekiwania na teleport (w sekundach)
tp-delay: 10

# [------------------------------]
# [            Motd
# [------------------------------]
# Czy ma siê pokazywaæ motd
motd-show: true
# Treœæ motd
motd:
 - '&8&m-------------------------------------'
 - '&7  Witaj &c{PLAYER}&7!'
 - '&7    Serwer uzywa &cqEssentials &7by &cxVacuum'
 - '&8&m-------------------------------------'
  
  
  
  
  
  
  
  
  


