# [------------------------------]
# [    qEssentials v0.1-DEV
# [  Dziêki za u¿ywanie! :)
# [  Wersja: PL / POLAND / POLSKA
# [------------------------------]

# [------------------------------]
# [      Podstawowe rzeczy 
# [------------------------------]
# Czy ma byæ w³¹czone szczegó³owe debugowanie (szczegó³owe informacje wysy³ane do konsoli)
debug: true
# Czy opcje wymagaj¹ce pluginu BarAPI maj¹ byæ w³¹czone
barapi: true
# G³ówne serwerowe motd
server-motd: '&7Plugin &cqEssentials &7by &cxVacuum&7!'
# Sloty (tylko wyœwietlane, nie prawdziwe!) Wpisz 0 aby wy³¹czyæ funkcjê.
server-slots: 120

# [------------------------------]
# [      Unknown command
# [------------------------------]
# Czy nieznana komenda w ogóle ma byæ w³¹czona
uc-enabled: true

uc-msg:
  - '&8&m-------------------------------------'
  - '    &7Nie znaleziono takiej komendy!'
  - '  &7Wpisz &c/help &7aby zobaczyc pomoc!'
  - '&8&m-------------------------------------'
  
 
# [------------------------------]
# [            Chat 
# [------------------------------]
# Format chatu
chat-format: '&8[{PREFIX}&8] &f{PLAYER}&8: &7{MESSAGE}'
# Wiadomoœæ wy³¹czania chatu
chat-off: '&7Chat zostal &cwylaczony&7!'
# Wiadomoœæ w³¹czania chatu
chat-on: '&7Chat zostal &cwlaczony&7!'
# Wiadomoœæ czyszczenia chatu
chat-clear: '&7Chat zostal &cwyczyszczony&7!'
# Czy ma byæ w³¹czona blokada URL ( - BETA!)
url-block: true
# Czy ma byæ w³¹czona blokada IP ( - BETA!)
ip-block: true
# Czy ma byæ w³¹czona blokada przekleñstw i nazw popularnych serwerów 
words-block: true
# Format chatu administratora
adminchat-format: '&8[&4@&8] &7{PLAYER}: &c{MESSAGE}'
# Czas pomiedzy mozliwoscia pisania w sekundach
slowdown: 5

# [------------------------------]
# [           Helpop
# [------------------------------]
# Co ile sekund mo¿na wysy³aæ /helpop 
helpop-delay: 30
# Format helpopu
helpop-format: '&8[&4Helpop&8] &7{PLAYER}: &c{MESSAGE}'

# [------------------------------]
# [           ChangeItem
# [------------------------------]
# Czym ma sie usuwac nazwe itemu lub opis
changeitem-remove: '-remove'

# [------------------------------]
# [         Join/Leave
# [------------------------------]
# Format dolaczania na serwer (zostaw '' jezeli chcesz wylaczyc)
join-format: '&c{PLAYER} &7dolaczyl do gry!'
# Format opuszczania serwera (zostaw '' jezeli chcesz wylaczyc)
leave-format: '&c{PLAYER} &7opuscil gre!'

# [------------------------------]
# [         Teleportation
# [------------------------------]
# Swiat w którym znajduje siê spawn
spawn-world: 'world'
# Okres oczekiwania na teleport (w sekundach)
tp-delay: 10

# [------------------------------]
# [       Startowe rzeczy
# [------------------------------]
# Czy ma siê pokazywaæ motd
motd-show: true
# Pierwsza wiadomosc o wejsciu gracza
first-message: '&7Witamy gracza &c{PLAYER} &7po raz pierwszy na serwerze!'
# Treœæ motd
motd:
 - '&8&m-------------------------------------'
 - '&7  Witaj &c{PLAYER}&7!'
 - '&7    Serwer uzywa &cqEssentials &7by &cxVacuum'
 - '&8&m-------------------------------------'
# Czy ma dawaæ startowe przedmioty 
start-items: true
# Startowe itemy
# Nazwa z bukkit'a, po malpie ilosc

items:
  - 'STONE_PICKAXE@1'
  - 'COOKED_BEEF@128'
  - 'ENDER_CHEST@1'
  - 'BOAT@2'

  
# [------------------------------]
# [            AutoMessage
# [------------------------------]
# Co ile ma byc wysylane automessage (w sekundach!)
am-delay: 60
# Automessage (tymczasowe) - zostaw puste je¿eli chcesz wy³¹czyæ
automessages:
  - '&8[&cqEssentials&8] &7Dziekuje za uzywanie pluginu! :D'
  - '&8[&cqEssentials&8] &7Wbijaj na &cMPC &7i ocen plugin!'
  - '&8[&cqEssentials&8] &7Masz propozycje? Wbijaj na &cgithub/xVacuum/qEssentials&7!'
  - '&8[&cqEssentials&8] &7Przykladowa losowa wiadomosc!'
  - '&8[&cqEssentials&8] &7Druga przykladowa wiadomosc!'
  
  
# [------------------------------]
# [          ClearItems
# [------------------------------]
# Czy ta funkcja ma byæ w³¹czona
clear-enabled: true

# Swiat który ma byæ wyczyszczony
clear-world: 'world'

# Pierwsza wiadomoœæ ostrzegaj¹ca przed czyszczeniem
clear-first: '&8[&cqEssentials | Clear&8] &7Za dokladnie &c{TIME} &7sekund odbedzie sie czyszczenie globalne!'

# Druga wiadomoœæ, ju¿ po wyczyszczeniu
clear-cleared: '&8[&cqEssentials | Clear&8] &7Wyczyszczono wszystkie przedmioty lezace na ziemi!'

# Ile sekund po ostrze¿eniu ma byæ czyszczony serwer
clear-delay-1: 30

# Co ile sekund ma byæ wykonywane czyszczenie itemów
clear-delay-2: 700

# [------------------------------]
# [          Kits
# [------------------------------]
kits:
  start:
    delay: 60
    items:
      - STONE_PICKAXE@1
      - ENDER_CHEST@1
      - COOKED_BEEF@128
      - BOAT@2
  vip:
    delay: 120
    items:
      - DIAMOND_PICKAXE@1
      - ENDER_CHEST@1
      - COOKED_BEEF@256
      - BOAT@3

# [------------------------------]
# [            MySQL
# [------------------------------]
# Typ zapisu plików
# flat = zapis do plików serwera 
# mysql = zapis do bazy danych (zalecane)
type: flat
# Dane mysql
mysql:
  host: localhost
  user: root
  password: ''
  database: qess
  port: 3306





