name: qEssentials
main: pl.za.xvacuum.qessentials.Main
version: 0.4-DEV
website: http://xvacuum.za.pl/qEssentials/
authors: [xVacuum(Dev), Fajny67(Tester), xBananowiec(Tester)]
depends: [Vault, PermissionsEx]