name: qEssentials
main: pl.za.xvacuum.qessentials.Main
version: 1.0-RELEASE
website: http://xvacuum.za.pl/qEssentials/
authors: [xVacuum(Dev), NTSW (Dev), Kresrek007 (Dev), cubeman (mini-dev), xSmokBezioxKox (tester)]
depends: [Vault, PermissionsEx]